name: Update staging from develop

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 1-5

jobs:
  develop-to-staging:
    name: Merge develop into staging every day
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'develop'
          target: 'admin'
