name: Cypress Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Logs
      run: |
        echo "AUTH_AUDIENCE=${{ secrets.CYPRESS_AUTH_AUDIENCE }}"
        echo "AUTH_URL=${{ secrets.CYPRESS_AUTH_URL }}"
        echo "AUTH_CLIENT_ID=${{ secrets.CYPRESS_AUTH_CLIENT_ID }}"
        echo "AUTH_CLIENT_SECRET=${{ secrets.CYPRESS_AUTH_CLIENT_SECRET }}"
        echo "AUTH_USERNAME_ADMIN=${{ secrets.CYPRESS_AUTH_USERNAME_ADMIN }}"
        echo "AUTH_PASSWORD_ADMIN=${{ secrets.CYPRESS_AUTH_PASSWORD_ADMIN }}"
        echo "AUTH_USERNAME=${{ secrets.CYPRESS_AUTH_USERNAME }}"
        echo "AUTH_PASSWORD=${{ secrets.CYPRESS_AUTH_PASSWORD }}"
        echo "API_URL=${{ secrets.CYPRESS_API_URL }}"

    - name: Cypress run
      uses: cypress-io/github-action@v6
      env:
        auth_audience: ${{ secrets.CYPRESS_AUTH_AUDIENCE }}
        auth_url: ${{ secrets.CYPRESS_AUTH_URL }}
        auth_client_id: ${{ secrets.CYPRESS_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CYPRESS_AUTH_CLIENT_SECRET }}
        auth_username_admin: ${{ secrets.CYPRESS_AUTH_USERNAME_ADMIN }}
        auth_password_admin: ${{ secrets.CYPRESS_AUTH_PASSWORD_ADMIN }}
        auth_username: ${{ secrets.CYPRESS_AUTH_USERNAME }}
        auth_password: ${{ secrets.CYPRESS_AUTH_PASSWORD }}
        apiURL: ${{ secrets.CYPRESS_API_URL }}
      with:
          build: npm run build
          start: npm start
          browser: chrome
