name: Cypress Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Logs
      run: |
        echo "La valeur de CYPRESS_AUTH_AUDIENCE est ${{ secrets.CYPRESS_AUTH_AUDIENCE }}"
        echo "La valeur de CYPRESS_AUTH_URL est ${{ secrets.CYPRESS_AUTH_URL }}"
        echo "La valeur de AUTH_CLIENT_ID est ${{ secrets.CYPRESS_AUTH_CLIENT_ID }}"
        echo "La valeur de AUTH_CLIENT_SECRET est ${{ secrets.CYPRESS_AUTH_CLIENT_SECRET }}"
        echo "La valeur de AUTH_USERNAME_ADMIN est ${{ secrets.CYPRESS_AUTH_USERNAME_ADMIN }}"
        echo "La valeur de AUTH_PASSWORD_ADMIN est ${{ secrets.CYPRESS_AUTH_PASSWORD_ADMIN }}"
        echo "La valeur de AUTH_USERNAME est ${{ secrets.CYPRESS_AUTH_USERNAME }}"
        echo "La valeur de AUTH_PASSWORD est ${{ secrets.CYPRESS_AUTH_PASSWORD }}"
        echo "La valeur de API_URL est ${{ secrets.CYPRESS_API_URL }}"
       
    - name: Cypress run
      uses: cypress-io/github-action@v6
      env:
        auth_audience: ${{ secrets.CYPRESS_AUTH_AUDIENCE }}
        auth_url: ${{ secrets.CYPRESS_AUTH_URL }}
        auth_client_id: ${{ secrets.CYPRESS_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CYPRESS_AUTH_CLIENT_SECRET }}
        auth_username_admin: ${{ secrets.CYPRESS_AUTH_USERNAME_ADMIN }}
        auth_password_admin: ${{ secrets.CYPRESS_AUTH_PASSWORD_ADMIN }}
        auth_username: ${{ secrets.CYPRESS_AUTH_USERNAME }}
        auth_password: ${{ secrets.CYPRESS_AUTH_PASSWORD }}
        apiURL: ${{ secrets.CYPRESS_API_URL }}
      with:
          build: npm run build
          start: npm start
          browser: chrome
