name: Cypress Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          build: npm run build
          start: npm start
          browser: chrome
